version: '3'
services:
  mysql-docker:
    image: mysql:8.0.38
    container_name: 'swyp-mysql'
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'gaezzange'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_USER: ${MYSQL_USER:-local}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
