version: '3'
services:
  mysql-docker:
    image: mysql:8.0.38
    container_name: 'swyp-mysql'
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'gaezzange'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_USER: ${MYSQL_USER:-local}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
 
  redis-docker:
    image: redis:7.2.5
    container_name: 'swyp-redis'
    command: redis-server --port 6379
    ports:
      - '6379:6379'
    volumes:
      - ./db/redis/data:/data
      - ./db/redis/conf/redis.conf:/usr/local/conf/redis.conf

  nginx-docker:
    image: nginx:latest
    container_name: 'swyp-nginx'
    environment:
      - HOST_PRIVATE_IP=${HOST_PRIVATE_IP}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mysql-docker
      - redis-docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge